#define OS_DARWIN	1
#define ARCH_ARM64	1
#define C_CLANG	1
#define __64BIT__	1
#define FUNDERSCORE	_
#define PTHREAD_CREATE_FUNC	pthread_create
#define BUNDERSCORE	_
#define NEEDBUNDERSCORE	1
#define ARMV8
#define L1_DATA_SIZE 32768
#define L1_DATA_LINESIZE 64
#define L2_SIZE 262144
#define L2_LINESIZE 64
#define DTB_DEFAULT_ENTRIES 64
#define DTB_SIZE 4096
#define L2_ASSOCIATIVE 32
#define CORE_ARMV8
#define CHAR_CORENAME "ARMV8"
#define GEMM_MULTITHREAD_THRESHOLD	4
